### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by dkazanc** [nikitinvv/tomocupy-stream#3]
Hi, I'm having this pip install issue, any ideas? thanks
```
(httomo) algol@home:~/Documents/OtherCODE/tomocupy-stream(main)$ pip install .
Processing /home/algol/Documents/OtherCODE/tomocupy-stream
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tomocupy-stream
  Building wheel for tomocupy-stream (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      cmake: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory
      Traceback (most recent call last):
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
          raise SKBuildError(
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tomocupy-stream
  Running setup.py clean for tomocupy-stream
Failed to build tomocupy-stream
Installing collected packages: tomocupy-stream
  Running setup.py install for tomocupy-stream ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for tomocupy-stream did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      cmake: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory
      Traceback (most recent call last):
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/home/algol/miniconda3/envs/httomo/lib/python3.10/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
          raise SKBuildError(
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tomocupy-stream

note: This is an issue with the package mentioned above, not pip.
```

**Comment by nikitinvv** [comment]
@dkazanc could you install cmake from conda? 
conda install -c conda-forge cmake

I've updated README accordingly

**Comment by dkazanc** [comment]
I've got cmake in my environment already... there are some related(?) [issues](https://github.com/scikit-build/cmake-python-distributions/issues/76) around that suggest that cmake should be pip installed (compiled) in a specific order?

Anyway in a new environment I've got this new error although `scikit-build` is already in the environment
```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/algol/miniconda3/envs/tomocupy/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/algol/miniconda3/envs/tomocupy/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/algol/miniconda3/envs/tomocupy/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i1s9p7q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-i1s9p7q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-i1s9p7q0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]
```

**Comment by nikitinvv** [comment]
looks strange, could you double check the environment? and then just try python -c 'import skbuild'. I typically install everyhting from conda-forge. could you try conda install -c conda-forge scikit-build?
I see python=3.11, maybe something is still missing it? could you try python=3.10

**Comment by zhangy6x** [comment]
Hi, I followed the installation instruction you provided, but still getting some error.
`Building wheels for collected packages: tomocupy_stream
  Building wheel for tomocupy_stream (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [122 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is GNU 13.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 13.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (0.9s)
      -- Generating done (0.0s)
      -- Build files have been written to: /SNS/users/y9z/Downloads/tomocupy-stream/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-build
        Command:
          /SNS/users/y9z/miniconda3/envs/tomocupy/bin/cmake /SNS/users/y9z/Downloads/tomocupy-stream -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-install -DPYTHON_VERSION_STRING:STRING=3.12.8 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/python3.12 -DPYTHON_INCLUDE_DIR:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/include/python3.12 -DPYTHON_LIBRARY:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/lib/libpython3.12.so -DPython_EXECUTABLE:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/python3.12 -DPython_ROOT_DIR:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/include/python3.12 -DPython_NumPy_INCLUDE_DIRS:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/numpy/_core/include -DPython3_EXECUTABLE:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/python3.12 -DPython3_ROOT_DIR:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/include/python3.12 -DPython3_NumPy_INCLUDE_DIRS:PATH=/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/numpy/_core/include -DCMAKE_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release
      
      Not searching for unused variables given on the command line.
      -- The CXX compiler identification is GNU 13.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Using SWIG as the Python extension wrapper.
      -- The CUDA compiler identification is NVIDIA 12.6.85 with host compiler GNU 13.3.0
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Found SWIG: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/swig4.0 (found version "4.3.0")
      CMake Warning (dev) at src/cuda/CMakeLists.txt:11 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonLibs: /SNS/users/y9z/miniconda3/envs/tomocupy/lib/libpython3.12.so (found version "3.12.8")
      -- Configuring done (3.3s)
      -- Generating done (0.1s)
      -- Build files have been written to: /SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-build
      [1/33] Swig compile cfunc_lprecfp16.i for python
      [2/33] Building CUDA object src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprec.cu.o
      FAILED: src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprec.cu.o
      /SNS/users/y9z/miniconda3/envs/tomocupy/bin/nvcc -forward-unknown-to-host-compiler -DHALF -Dcfunc_lprecfp16_EXPORTS -I/SNS/users/y9z/Downloads/tomocupy-stream/src/include -I/SNS/users/y9z/miniconda3/envs/tomocupy/targets/x86_64-linux/include -I/SNS/users/y9z/miniconda3/envs/tomocupy/include/python3.12 -O3 -DNDEBUG -std=c++17 "--generate-code=arch=compute_60,code=[compute_60,sm_60]" "--generate-code=arch=compute_72,code=[compute_72,sm_72]" "--generate-code=arch=compute_75,code=[compute_75,sm_75]" "--generate-code=arch=compute_80,code=[compute_80,sm_80]" -Xcompiler=-fPIC -MD -MT src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprec.cu.o -MF src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprec.cu.o.d -x cu -c /SNS/users/y9z/Downloads/tomocupy-stream/src/cuda/cfunc_lprec.cu -o src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprec.cu.o
      In file included from /SNS/users/y9z/Downloads/tomocupy-stream/src/cuda/cfunc_lprec.cu:1:
      /SNS/users/y9z/Downloads/tomocupy-stream/src/include/cfunc_lprec.cuh:4:10: fatal error: cufft.h: No such file or directory
          4 | #include <cufft.h>
            |          ^~~~~~~~~
      compilation terminated.
      [3/33] Building CXX object src/cuda/CMakeFiles/cfunc_lprecfp16.dir/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx.o
      FAILED: src/cuda/CMakeFiles/cfunc_lprecfp16.dir/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx.o
      /SNS/users/y9z/miniconda3/envs/tomocupy/bin/x86_64-conda-linux-gnu-c++ -DHALF -Dcfunc_lprecfp16_EXPORTS -I/SNS/users/y9z/Downloads/tomocupy-stream/src/include -I/SNS/users/y9z/miniconda3/envs/tomocupy/include/python3.12 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /SNS/users/y9z/miniconda3/envs/tomocupy/include  -I/SNS/users/y9z/miniconda3/envs/tomocupy/targets/x86_64-linux/include -O3 -DNDEBUG -fPIC -MD -MT src/cuda/CMakeFiles/cfunc_lprecfp16.dir/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx.o -MF src/cuda/CMakeFiles/cfunc_lprecfp16.dir/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx.o.d -o src/cuda/CMakeFiles/cfunc_lprecfp16.dir/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx.o -c /SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-build/src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx
      In file included from /SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-build/src/cuda/CMakeFiles/cfunc_lprecfp16.dir/cfunc_lprecfp16PYTHON_wrap.cxx:3357:
      /SNS/users/y9z/Downloads/tomocupy-stream/src/include/cfunc_lprec.cuh:4:10: fatal error: cufft.h: No such file or directory
          4 | #include <cufft.h>
            |          ^~~~~~~~~
      compilation terminated.
      [4/33] Swig compile cfunc_fourierrec.i for python
      [5/33] Swig compile cfunc_fourierrecfp16.i for python
      [6/33] Swig compile cfunc_linerec.i for python
      [7/33] Swig compile cfunc_filterfp16.i for python
      [8/33] Swig compile cfunc_linerecfp16.i for python
      [9/33] Swig compile cfunc_filter.i for python
      [10/33] Swig compile cfunc_lprec.i for python
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 668, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/skbuild/cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/SNS/users/y9z/miniconda3/envs/tomocupy/lib/python3.12/site-packages/skbuild/cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /SNS/users/y9z/miniconda3/envs/tomocupy/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /SNS/users/y9z/Downloads/tomocupy-stream
        Working directory:
          /SNS/users/y9z/Downloads/tomocupy-stream/_skbuild/linux-x86_64-3.12/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tomocupy_stream
  Running setup.py clean for tomocupy_stream
Failed to build tomocupy_stream
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tomocupy_stream)
`
python version 3.12.8
cmake version 3.31.2
nvcc: release 12.6, V12.6.85 Build cuda_12.6.r12.6/compiler.35059454_0

**Comment by nikitinvv** [comment]
@zhangy6x it seems you are trying to use the cuda compiler installed from conda:
`-- Check for working CUDA compiler: /SNS/users/y9z/miniconda3/envs/tomocupy/bin/nvcc - skipped`
 It is probably installed without headers since the error is:
`4 | #include <cufft.h>`

Could you check other installation of cuda compilers on your system? Maybe you need to add cuda as module.

You can find other compilers with:
`locate nvcc  `

Then you can set smth like 
`export CUDACXX=/local/cuda-11.4/bin/nvcc`

and do pip install .

**Comment by zhangy6x** [comment]
@nikitinvv thank you! It works for me now.
